spring.datasource.url=${SPRING_DATASOURCE_URL:jjdbc:postgresql://ep-divine-union-atuvsnzt-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_XEoSqz74tNyb&sslmode=require&channelBinding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pg_AGiJT9Q4REIx}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.flyway.enabled=false
ep-royal-pine-atjnu75i-pooler.c-9.us-east-1.aws.neon.tech

